export const kanye_quotes = [
  "I refuse to accept other people's ideas of happiness for me.",
  "As if there's a one size fits all standard for happiness.",
  "We came into a broken world.",
  "And we're the cleanup crew.",
  "We all self-conscious.",
  "I'm just the first to admit it.",
  "George Bush doesn't care about black people.",
  "I would hear stories about Steve Jobs and feel like he was at 100 percent exactly what he wanted to do, but I'm sure even a Steve Jobs has compromised.",
  "Even a Rick Owens has compromised.",
  "You know, even a Kanye West has compromised.",
  "Sometimes you don't even know when you're being compromised till after the fact, and that's what you regret.",
  "I am Warhol.",
  "I am the Number 1 most impactful artist of our generation.",
  "I am Shakespeare in the flesh.",
  "I have decided in 2020 to run for president.",
  "Here's something that's contrary to popular belief: I actually don't like thinking.",
  "I think people think I like to think a lot.",
  "And I don't.",
  "I do not like to think at all.",
  "Blacks, especially in America, have been raised with a slave mentality; they don't feel that they have the right to speak as loud as possible.",
  "Know your worth.",
  "People always act like they're doing more for you than you're doing for them.",
  "For me, money is not my definition of success.",
  "Inspiring people is a definition of success.",
  "Nothing in life is promised except death.",
  "If you have the opportunity to play this game of life you need to appreciate every moment.",
  "a lot of people don't appreciate the moment until it's passed.",
  "I ain't here to argue about his facial features.",
  "Or here to convert atheists into believers.",
  "I'm just trying to say the way school need teachers the way Kathie Lee needed Regis that's the way yall need Jesus.",
  "I know I got angels watchin me from the other side.",
  "They say you can rap about anything except for Jesus, that means guns, sex, lies, video tapes, but if I talk about God my record won't get played Huh.",
  "I don't know what's better gettin' laid or gettin' paid.",
  "This dark diction has become America's addiction.",
  "I'll say things that are serious and put them in a joke form so people can enjoy them.",
  "We laugh to keep from crying.",
  "People always say that you can't please everybody.",
  "I think that's a cop-out.",
  "Why not attempt it.",
  "Cause think of all the people you will please if you try.",
  "It was a strike against me that I didn't wear baggy jeans and jerseys and that I never hustled, never sold drugs.",
  "But for me to have the opportunity to stand in front of a bunch of executives and present myself, I had to hustle in my own way.",
  "I can't tell you how frustrating it was that they didn't get that.",
  "No joke, I'd leave meetings crying all the time.",
  "I didn't want to play it boring and safe.",
  "I also didn't want to innovate too much.",
  "Second albums, man, they're even scarier than first ones.",
  "I'm pretty calculating.",
  "I take stuff that I know appeals to people's bad sides and match it up with stuff that appeals to their good sides.",
  "Black people can be the most conservative, the most discriminating.",
  "Especially among ourselves.",
  "It wasn't white people who said all black men have to wear baggy jeans.",
  "Michael Jordan changed so much in basketball, he took his power to make a difference.",
  "It's so much going on in music right now and somebody has to make a difference.",
  "The concept of commercialism in the fashion and art world is looked down upon.",
  "You know, just to think, what amount of creativity does it take to make something that masses of people like.",
  "And, how does creativity apply across the board.",
  "Why, if someone is good in one field can they not be accepted or given the slightest opportunity to express and be creative in other fields.",
  "Fashion breaks my heart.",
  "Thirty-three-years-old, still creating art.",
  "It's rage, it's creativity, it's pain, it's hurt, but it's the opportunity to still have my voice get out there through music.",
  "I thank Marc Jacobs so much for giving me the opportunity to design a shoe for Louis Vuitton, but the thing that broke my heart most was when they said,you're finished.",
  "The shoe's finished.",
  "Keep your nose out the sky, keep your heart to god, and keep your face to the raising sun.",
  "Our work is never over.",
  "I was never really good at anything except for the ability to learn.",
  "I can always tell if a band has a British rhythm section due to the gritty production.",
  "I hate the way they portray us in the media.",
  "If you see a black family it says they're looting, if you see a white family it says they're looking for food.",
  "I still think I am the greatest.",
  "Would you believe in what you believe in if you were the only one who believed it.",
  "I am not a fan of books.",
  "I would never want a book's autograph.",
  "I am a proud non-reader of books.",
  "I don't even listen to rap.",
  "My apartment is too nice to listen to rap in.",
  "Sometimes people write novels and they just be so wordy and so self-absorbed.",
  "I am God's vessel.",
  "But my greatest pain in life is that I will never be able to see myself perform live.",
  "I feel like I'm too busy writing history to read it.",
  "If I was just a fan of music, I would think that I was the number one artist in the world.",
  "I will go down as the voice of this generation, of this decade, I will be the loudest voice.",
  "I really appreciate the moments that I was able to win rap album of the year or whatever.",
  "My message isn't perfectly defined.",
  "I have, as a human being, fallen to peer pressure.",
  "Creative output, you know, is just pain.",
  "I'm going to be cliche for a minute and say that great art comes from pain.",
  "I liberate minds with my music.",
  "That's more important than liberating a few people from apartheid or whatever.",
  "You don't have to be scared of me, because I am loyal.",
  "Why are people so scared of creative ideas and so scared of truth.",
  "All I want to do is do good.",
  "I think I do myself a disservice by comparing myself to Steve Jobs and Walt Disney and human beings that we've seen before.",
  "It should be more like Willy Wonka, and welcome to my chocolate factory.",
  "In Paris, you're as far as possible from the land of pleasant smiles.",
  "Man, I'm the Number 1 living and breathing rock star.",
  "I am Axl Rose; I am Jim Morrison; I am Jimi Hendrix.",
  "Nobody can tell me where I can and can't go.",
  "I told y'all I didn't vote, right.",
  "But if I would've voted, I would've voted for Trump.",
  "People always tell you, Be humble, Be humble",
  "When was the last time someone told you to be amazing.",
  "Be great.",
  "Be great.",
  "Be awesome.",
  "I'm giving all that I have in this life.",
  "I'm opening up my notebook, and I'm saying everything in there out loud.",
  "The risk for me would be in not taking one; that's the only thing that's really risky for me.",
  "I'm a trained fine artist.",
  "I went to art school from the time I was 5 years old.",
  "I was, like, a prodigy out of Chicago.",
  "I'd been in national competitions from the age of 14.",
  "Madonna, I think, is the greatest visual musical artist that we've ever had.",
  "If you look at her photo log, the photographers that she was able to work with throughout her career framed her in the proper way.",
  "It was the proper context.",
  "It was that visual that made sure that everything was gonna cut through in a certain way.",
  "Sometimes we be playing the politics too much and forget who we are just to win.",
  "I'm not always going to say things the perfect way, the right way.",
  "But I'm going to say how I feel.",
  "There's a lack of people in power that are motivated by the idea of helping people.",
  "In today's world, having money has allowed people who are extremely uncool to think that they're cool and carry it like that.",
  "People who really are cool and people who really are artists and have ideas have to literally turn in their cool card to society just to make it past the age of 28.",
  "I wouldn't say that anyone in fashion is on my side.",
  "I don't think there's anyone on my side.",
  "I'm inspired by Walt Disney.",
  "I'm inspired by Howard Hughes.",
  "I'm inspired by Henry Ford.",
  "I'm inspired by Steve Jobs.",
  "I mean, I'm inspired by James Perse.",
  "My goal is just to be respected as a man when I walk down the street with my family.",
  "I don't care what your job is, you're not gonna talk down to me, you're not gonna try to get a rise out of me.",
  "I'm a man first.",
  "And in establishing that, some interesting things have happened.",
  "People have me pinned as a shark or a predator in some way, and in no way am I that.",
  "I wouldn't want to hurt anyone.",
  "I want to defend people.",
  "I want to help people.",
  "I'm here to fight for the re-education of what celebrity is: to say, yes, we are celebrities, but yes, we're also innovators.",
  "We're also inventors.",
  "We're also thoughtful. ",
  "The concept of Kimye has more cultural significance than what Page Six could write.",
  "My favorite record label of all time is Motown.",
  "That era of music was my favorite.",
  "All these walls that keep us from loving each other as one family or one race, racism, religion, where we grew up, whatever, class, socioeconomic, what makes us be so selfish and prideful, what keeps us from wanting to help the next man, what makes us be so focused on a personal legacy as opposed to the entire legacy of a race.",
  "The dinosaurs aren't remembered for much more than their bones.",
  "When humanity's gone, what do we give to this little planet that we're on, and what could we do collectively, removing the pride.",
  "Every time I say something that's extremely truthful out loud, it literally breaks the Internet.",
  "Our focus needs to be less on what our legacy's going to be or how we can control each other and more how we can give to each other.",
  "I can analyze people's intentions.",
  "Immediately.",
  "That's just a warning.",
  "To everyone.",
  "I used to have insecurity about my finances, then I announced that I had debt, and now I don't have any insecurities.",
  "I love sleep; it's my favorite.",
  "I don't use blue.",
  "I don't like it.",
  "It bugs me out.",
  "I hate it.",
  "If we go on your iPhone and go to the dictionary and look up humble, 80 percent of the definition is negative.",
  "It's a controlling word.",
  "It's a way to control the masses and to control the sheep.",
  "It's always going to be a fight for anyone who isn't an older white man.",
  "I want to fight for anyone who doesn't have a fight.",
  "I just want people to be the best thems and live the happiest lives possible.",
  "There was a time Michael Jackson couldn't get his video on MTV because he was considered to be urban",
  "So I literally have to be the Michael Jackson of apparel in order to break down the doors for everyone who will come after I'm gone, after I'm dead.",
  "We're a blip in the existence of the universe, and we're constantly trying to pull each other down.",
  "Not doing things to help each other.",
  "I know how to swim through backlash.",
  "I can tread water through backlash.",
  "If anything, that's all giving me power.",
  "The most genius thing about the way I create is to create with other geniuses.",
  "You know what should be banned.",
  "Stuff that's whack.",
  "The world is controversial.",
  "The world is classist.",
  "The world is racist.",
  "I love being American, and I love family.",
  "I love having a family, and I feel so blessed, and I feel like God gave me exactly what I wanted, so now I have to do the right thing in God's eyes also.",
  "Just follow what God wants me to do.",
  "I didn't know the term synesthesia until I was working on Cruel Summer.",
  "Halfway into writing that, I really understood that, my entire life, I had been trying to describe this condition of mine: through painting, through this seven-screen Surround Vision film we shot in Qatar, through all these things.",
  "I'm really bad with answering questions.",
  "Usually, I don't even answer them.",
  "I try to find inspiration inside of the question.",
  "I think, and I jump from one beam of inspiration or energy to the next, as opposed to explaining the energy.",
  "I'm a human being.",
  "I've got opinions, I'm not always right, I'm not always on time, I don't always say things in the proper way, but my intentions are always extremely pure.",
  "I dislike the concept of chic being the highest compliment for a human being.",
  "I'd rather someone be nice than to be chic.",
  "Fashion is merely an opinion.",
  "And I've got a lot of opinions.",
  "Art is to be free.",
  "Design is to fix.",
  "My doorman is more important to me than any head of any company.",
  "He keeps us safe.",
  "I definitely think, generally, rap is misogynistic.",
  "Do I worry about being in the public eye and raising kids.",
  "Yeah.",
  "Any situation you're in, you're gonna worry about raising kids.",
  "But it's champagne problems, too.",
  "There are people who can't feed their kids.",
  "I don't think people are going to talk in the future.",
  "They're going to communicate through eye contact, body language, emojis, signs.",
  "It's funny because I've made a living off of words, but words get in the way of what you really want to say.",
  "I think business has to be stupider.",
  "I want to do really straightforward, stupid business, just talk to me like a 4-year-old.",
  "And I refuse to negotiate.",
  "I do not negotiate.",
  "I can collaborate.",
  "But I'm an artist, so as soon as you negotiate, you're being compromised.",
  "It's not can, it's will, you have to will things into fruition.",
  "We all self-conscious.",
  "I'm just the first to admit it.",
  "My greatest pain in life is that I will never be able to see myself perform life.",
  "Keep your nose out the sky, keep your heart to god, and keep your face to the rising sun.",
  "I care.",
  "I care about everything.",
  "Sometimes not giving a f#%k is caring the most.",
  "My greatest award is what I'm about to do.",
  "Recognize and embrace your flaws so you can learn from them.",
  "Sometimes it takes a little polishing to truly shine.",
  "Believe in your flynes, conquer your shyness.",
  "If you have the opportunity to play this game of life you need to appreciate every moment.",
  "A lot of people don't appreciate the moment until it's passed.",
  "People always say that you can't please everybody.",
  "I think that's a cop-out.",
  "Why not attempt it.",
  "‘Cause think of all the people that you will please if you try.",
  "People say I have a bad reputation.",
  "I think I've got the best reputation in the building.",
  "I'm on the pursuit of awesomeness, excellence is the bare minimum.",
  "I feel that I'm very blessed.",
  "But with great blessings come great responsibility.",
  "Living well eliminates the need for revenge.",
  "If I don't scream, if I don't say something then no one's going to say anything.",
  "Why are people so afraid of creative ideas and so scared of truth.",
  "All I want to do is do good.",
  "I'm not comfortable with comfort.",
  "I'm only comfortable when I'm in a place where I'm constantly learning and growing.",
  "One of my biggest Achilles heels has been my ego.",
  "And if I, Kanye West, can remove my ego, I think there's hope for everyone.",
  "I always feel like I can do anything.",
  "That's the main thing people are controlled by: thoughts and perceptions of yourself.",
  "If you're taught you can't do anything, you won't do anything.",
  "Be great.",
  "Be awesome.",
  "Be awesome.",
  "Justice could just be clearing a path for people to dream properly.",
  "For me giving up is way harder than trying.",
  "Most people are slowed down by the perception of themselves.",
  "If you're taught you can't do anything, you won't do anything.",
  "I was taught I can do everything.",
  "I want people to feel like it's okay to create.",
  "It's okay to not be boxed in.",
  "I want people to feel like awesome is possible.",
  "I refuse to accept other people's ideas of happiness for me.",
  "As if there's a ‘one size fits all' standard for happiness.",
  "People will have a problem with whatever you do.",
  "At the end of the day, nobody can determine what you need to do in order to be successful and why would you listen to someone who is not successful tell you what you need to do.",
  "When you're the absolute best, you get hated on the most.",
  "People never change.",
  "They just become better at hiding who they really are.",
  "They say people in your life are seasons and anything that happens is for a reason.",
  "Memories have to be our most painful blessing.",
  "I think I do myself a disservice by comparing myself to Steve Jobs and Walt Disney and human beings that we've seen before.",
  "You can't look at a glass half full or empty if it's overflowing.",
  "I want the world to be better.",
  "All I want is positive.",
  "All I want is dopeness.",
  "You've got to be really dialled into exactly who you are to the one hundredth power of you're just like everyone else.",
  "Criticism can bother you, but you should be more bothered if there's no criticism.",
  "That means you're too safe.",
  "People say I have a bad reputation I think I've got the best reputation in the building.",
  "They want you to have a reputation of tucking your black nail polish into your pockets and sitting in the corner of the class, and not fighting for your ideas out of fear of being ridiculed.",
  "That's one of my favourite ones…to be called crazy.",
  "For me, you know, I'm a creative genius and there's no other way to word it.",
  "50 is Eminem's favourite rapper… I'm my favourite rapper.",
  "I will go down as the voice of this generation, of this decade I will be the loudest voice.",
  "My greatest pain in life is that I'll never be able to see myself perform live.",
  "I am a God, so hurry up with my damn massage in a French-ass restaurant, hurry up with my damn croissants.",
  "I am flawed as a human.",
  "I am flawed as a person.",
  "As a man I am flawed but my music is perfect.",
  "You basically can say anything to someone on an email or text as long as you put LOL at the end.",
  "When I think of competition it's like I try to create against the past I think about Michelangelo and Picasso, you know, the pyramids.",
  "I just think that when my confidence meets other people's insecurity that equals Kanye's arrogant.",
  "I'm like a vessel, and God has chosen me to be the voice and the connector.",
  "It's like this, by not giving my album a classic rating you diminish your magazine's credibility.",
  "And that's real."
];
